sudo: required
services:
  - docker

before_install:
  - docker build -t tuliomonteiro/docker-react -f Dockerfile.dev .

script:
  - docker run tuliomonteiro/docker-react npm run test -- --coverage

deploy:
  provider: elasticbeanstalk
  region: "us-west-2"
  app: "docker-react"
  env:  "DockerReact-env"
  bucket_name: "elasticbeanstalk-us-west-2-760877605459"
  bucket_path: "docker-react"
  on:
    brach: master
  access_key_id: $AWS_ACCESS_KEY
  secret_access_key:
    secure: "$AWS_SECRET_KEY"
